name: Mule CI Build

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Runner
        run: |
          echo "Runner is Online"
          hostname
          whoami
          pwd

      - name: Verify Java
        run: java -version

      - name: Verify Maven
        run: mvn -version
