name: Mule CI Build

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Runner
        run: |
          echo "Runner is Online"
          hostname
          whoami
          pwd

      - name: Verify Java
        run: java -version

      - name: Verify Maven
        run: mvn -version

      - name: Build Mule Application
        run: |
          mvn clean package

      - name: Verify Build Output
        run: |
          ls -lh target

      - name: Deploy to Mule Runtime
        run: |
          sudo cp target/*.jar /opt/mule/mule-enterprise-standalone-4.9.8/apps/

      - name: Verify Deployment
        run: |
          ls -lh /opt/mule/mule-enterprise-standalone-4.9.8/apps/
